###

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "tickerDto": "APPL",
  "date" : "2023-12-24T18:36:24.00Z",
  "quantity": 5,
  "price": 200.0,
  "transactionType": "BUY",
  "currency": "USD"
}

###

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "tickerDto": "MSFT",
  "date" : "2022-12-25T18:36:24.00Z",
  "quantity": 5,
  "price": 200.0,
  "transactionType": "BUY",
  "currency": "USD"
}

###

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "tickerDto": "APPL",
  "date" : "2023-08-25T18:36:24.00Z",
  "quantity": 5,
  "price": 200.0,
  "transactionType": "SELL",
  "currency": "USD"
}

###

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "tickerDto": "MSFT",
  "date" : "2024-04-25T18:36:24.00Z",
  "quantity": 5,
  "price": 200.0,
  "transactionType": "BUY",
  "currency": "USD"
}

###

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "tickerDto": "APPL",
  "date" : "2023-12-25T18:36:24.00Z",
  "quantity": 5,
  "price": 200.0,
  "transactionType": "SELL",
  "currency": "USD"
}

###

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "tickerDto": "APPL",
  "date" : "2023-12-25T18:36:24.00Z",
  "quantity": 5,
  "price": 300.0,
  "transactionType": "BUY",
  "currency": "USD"
}

###

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "tickerDto": "NET",
  "date" : "2023-12-25T18:36:24.00Z",
  "quantity": 5,
  "price": 200.0,
  "transactionType": "BUY",
  "currency": "USD"
}

###

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "tickerDto": "INTL",
  "date" : "2023-12-25T18:36:24.00Z",
  "quantity": 5,
  "price": 300.0,
  "transactionType": "BUY",
  "currency": "USD"
}

###

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "tickerDto": "QQQ",
  "date" : "2023-12-25T18:36:24.00Z",
  "quantity": 5,
  "price": 200.0,
  "transactionType": "BUY",
  "currency": "USD"
}