server:
  port: 8020

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketdata
    username: market-svc
    password: market-pass
    hikari:
      maximum-pool-size: 20       # Maximum number of connections in the pool
      minimum-idle: 10            # Minimum number of idle connections in the pool
      idle-timeout: 30000         # Maximum idle time before a connection is closed (in milliseconds)
      connection-timeout: 20000   # Maximum time to wait for a connection from the pool (in milliseconds)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      #      ddl-auto: update
      ddl-auto: create-drop

    properties:
      hibernate:
        default_schema: marketdata_schema




data:
  marketstack:
    url: http://localhost:8080 # Wiremock stub server
    apikey: "xxx"